/**
 * Render pool (PLAN_V3 4.1) — a pool of node child processes (fork of the
 * generated worker artifact) that keeps compose + render OFF the Next.js
 * event loop. fork() instead of worker_threads: Turbopack statically detects
 * `new Worker(...)` and mis-traces the whole app tree into the route graph
 * ("Unknown module type" for dev.log/wav/py); child_process is not pattern-
 * detected. serialization:'advanced' carries Float32Arrays over IPC.
 *
 * - One idle round-robin dispatcher over N workers (N = clamp(cpus-1, 1, 4)).
 * - Jobs are queued when every worker is busy; the queue is BOUNDED — beyond
 *   `maxQueue` the request fails fast (honest 503 upstream) instead of
 *   silently piling up unbounded memory.
 * - A worker that dies (crash/OOM) is replaced once; repeated death trips a
 *   permanent kill-switch so the route falls back to in-thread rendering
 *   (honest degraded mode) instead of crash-looping.
 * - The worker artifact (apps/web/workers/render-worker.mjs) is GENERATED by
 *   scripts/build-render-worker.mjs. If it is missing, `isAvailable()` is
 *   false and callers fall back — the pool never blocks boot.
 */
import { fork } from 'node:child_process'
import type { ChildProcess } from 'node:child_process'
import { existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

// CWD-INDEPENDENT artifact resolution: the worker file is a GENERATED
// artifact at apps/web/workers/render-worker.mjs. Under bun/test the module
// runs from source (module-relative works); under next dev the route may be
// transformed into .next chunks (import.meta.url lies), so we also probe
// cwd-based candidates. First existing path wins.
const THIS_DIR = dirname(fileURLToPath(import.meta.url))
const ARTIFACT_CANDIDATES = [
  join(THIS_DIR, '..', '..', '..', 'workers', 'render-worker.mjs'),
  join(process.cwd(), 'workers', 'render-worker.mjs'),
  join(process.cwd(), 'apps', 'web', 'workers', 'render-worker.mjs'),
]
function resolveArtifact(): string | null {
  for (const candidate of ARTIFACT_CANDIDATES) {
    if (existsSync(candidate)) return candidate
  }
  return null
}

/** Mirrors WorkerRenderJob (apps/web/src/workers/render-worker.ts) — inlined
 * here so the pool has NO module dependency on the worker source: importing
 * it made Turbopack bundle the whole render pipeline (and its dynamic
 * imports) into the route graph. Keep in sync with the worker entry. */
export interface PoolJob {
  id: number
  bars: number
  seed: number
  useSamples: boolean
  bpm: number
  wantStems: boolean
  ctx: Record<string, unknown>
  config: Record<string, number>
}

interface WorkerRenderOk extends Omit<PoolJob, 'ctx' | 'config'> {
  ok: true
  samplesL: Float32Array
  samplesR: Float32Array
  sampleRate: number
  durationSec: number
  events: number
  lufs: number
  truePeakDb: number
  samplePeakDb: number
  stereoWidth: number
  monoCompatibility: number
  gainReductionDb: number
  stems: null | Record<string, Float32Array>
}

interface WorkerRenderErr {
  id: number
  ok: false
  error: string
}

type WorkerRenderReply = WorkerRenderOk | WorkerRenderErr

export interface PoolOptions {
  size?: number
  maxQueue?: number
}

interface Pending {
  resolve: (reply: Extract<WorkerRenderReply, { ok: true }>) => void
  reject: (err: Error) => void
}

function defaultSize(): number {
  const cpus = 4 // honest default for the sandbox; overridable via PoolOptions
  return Math.max(1, Math.min(4, cpus - 1))
}

export class RenderPool {
  readonly size: number
  readonly maxQueue: number
  private readonly workers: Array<ChildProcess | null> = []
  private readonly idle: number[] = []
  private readonly pending = new Map<number, Pending>()
  private readonly queue: Array<{ job: PoolJob; pending: Pending }> = []
  private nextId = 1
  private disposed = false
  private workerDeaths = 0
  private killed = false

  constructor(opts: PoolOptions = {}) {
    this.size = opts.size ?? defaultSize()
    this.maxQueue = opts.maxQueue ?? 16
  }

  /** True when the built worker artifact exists and the pool is not killed. */
  isAvailable(): boolean {
    return !this.killed && !this.disposed && resolveArtifact() !== null
  }

  /** True when repeated worker deaths forced degraded (in-thread) mode. */
  get degraded(): boolean {
    return this.killed
  }

  private spawn(index: number): ChildProcess {
    const artifact = resolveArtifact()
    if (!artifact) throw new Error('render worker artifact missing')
    const worker = fork(artifact, [], { serialization: 'advanced', stdio: 'ignore' })
    worker.unref()
    worker.on('message', (reply: WorkerRenderReply) => {
      const pending = this.pending.get(reply.id)
      if (pending) {
        this.pending.delete(reply.id)
        if (reply.ok) pending.resolve(reply)
        else pending.reject(new Error(reply.error))
        this.idle.push(index)
        this.drain()
      }
    })
    worker.on('error', () => {
      this.handleWorkerDeath(index)
    })
    worker.on('exit', (code) => {
      if (code !== 0 && !this.disposed) this.handleWorkerDeath(index)
    })
    return worker
  }

  private handleWorkerDeath(index: number): void {
    if (this.disposed) return
    for (const [id, pending] of this.pending) {
      this.pending.delete(id)
      pending.reject(new Error('render worker died mid-render'))
    }
    this.workers[index] = null
    this.workerDeaths++
    // Reboot once per slot; repeated death kills the pool permanently (honest
    // degraded mode: the route falls back to in-thread rendering).
    if (this.workerDeaths <= this.size) {
      this.workers[index] = this.spawn(index)
      this.idle.push(index)
      this.drain()
    } else {
      this.killed = true
    }
  }

  private ensureSpawned(): void {
    for (let i = 0; i < this.size; i++) {
      if (!this.workers[i]) {
        this.workers[i] = this.spawn(i)
        this.idle.push(i)
      }
    }
  }

  private dispatchTo(index: number, entry: { job: PoolJob; pending: Pending }): void {
    const worker = this.workers[index]
    if (!worker) {
      // Slot lost between idle-pop and post — park back and let death handling retry.
      this.idle.push(index)
      return
    }
    this.pending.set(entry.job.id, entry.pending)
    worker.send(entry.job)
  }

  private drain(): void {
    while (this.queue.length > 0 && this.idle.length > 0) {
      const index = this.idle.shift()
      const entry = this.queue.shift()
      if (index === undefined || entry === undefined) return
      this.dispatchTo(index, entry)
    }
  }

  /**
   * Submit a render job. Resolves with the render outcome, or rejects with:
   * - 'render worker died mid-render' (worker crash),
   * - 'render queue full (N)' (backpressure — caller maps to 503).
   */
  render(job: Omit<PoolJob, 'id'>): Promise<Extract<WorkerRenderReply, { ok: true }>> {
    if (this.disposed) return Promise.reject(new Error('render pool disposed'))
    if (!this.isAvailable()) return Promise.reject(new Error('render worker artifact missing'))
    if (this.queue.length >= this.maxQueue) {
      return Promise.reject(new Error(`render queue full (${this.maxQueue})`))
    }
    this.ensureSpawned()
    const fullJob: PoolJob = { ...job, id: this.nextId++ }
    return new Promise((resolve, reject) => {
      this.queue.push({ job: fullJob, pending: { resolve, reject } })
      this.drain()
    })
  }

  get stats(): { size: number; queued: number; busy: number; deaths: number; killed: boolean } {
    return {
      size: this.size,
      queued: this.queue.length,
      busy: this.pending.size,
      deaths: this.workerDeaths,
      killed: this.killed,
    }
  }

  dispose(): void {
    this.disposed = true
    for (const [id, pending] of this.pending) {
      this.pending.delete(id)
      pending.reject(new Error('render pool disposed'))
    }
    // Queued-but-not-started jobs must also be rejected, not silently dropped.
    for (const entry of this.queue) {
      entry.pending.reject(new Error('render pool disposed'))
    }
    for (const w of this.workers) w?.kill()
    this.workers.fill(null)
    this.queue.length = 0
  }
}

// ── module-level singleton (Next.js route modules reload; the pool must not) ─
const globalForPool = globalThis as unknown as { __psyRenderPool?: RenderPool }

export function getRenderPool(): RenderPool {
  if (!globalForPool.__psyRenderPool) {
    globalForPool.__psyRenderPool = new RenderPool()
  }
  return globalForPool.__psyRenderPool
}
