#!/usr/bin/env bun
/**
 * DECISIONS_V3 D6 — build the psy4 AudioWorklet from its TypeScript SOURCE.
 *
 * Source:      apps/web/src/worklets/psy4-processor.ts
 * Artifact:    apps/web/public/worklets/psy4-processor.js  (committed, but
 *              GENERATED — the file carries a DO NOT EDIT banner)
 *
 * The worklet imports its DSP primitives from @psy-foundation/dsp, so the
 * bundle inlines the ONE canonical implementation (master chain, PolyBLEP,
 * ZDF SVF) — the 4th hand-maintained DSP copy is gone.
 *
 * After building, this script asserts:
 *   1. the output registers the 'psy4-processor' AudioWorkletProcessor, and
 *   2. the output is syntactically valid JS (`node --check`).
 *
 * Reproducibility gate (charter): two consecutive builds must be
 * byte-identical. Run this script twice and compare md5, e.g.:
 *   bun scripts/build-worklet.mjs && md5sum apps/web/public/worklets/psy4-processor.js
 *   bun scripts/build-worklet.mjs && md5sum apps/web/public/worklets/psy4-processor.js
 */

import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { readFileSync, statSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const entrypoint = join(repoRoot, 'apps/web/src/worklets/psy4-processor.ts')
const outdir = join(repoRoot, 'apps/web/public/worklets')
const naming = 'psy4-processor.js'

// PLAN_V3 3.1 — the artifact carries the release version (single source:
// packages/dsp/src/version.ts). verify.mjs greps this line back out and fails
// the 'release-version-integrity' claim on any mismatch.
const versionTs = readFileSync(join(repoRoot, 'packages/dsp/src/version.ts'), 'utf8')
const versionMatch = versionTs.match(/FOUNDATION_VERSION\s*=\s*'([^']+)'/)
if (!versionMatch) {
  console.error(
    'worklet build FAILED: could not read FOUNDATION_VERSION from packages/dsp/src/version.ts'
  )
  process.exit(1)
}
const FOUNDATION_VERSION = versionMatch[1]

const banner = `/* GENERATED by scripts/build-worklet.mjs — DO NOT EDIT. Source: apps/web/src/worklets/psy4-processor.ts. Version: ${FOUNDATION_VERSION} */\n/* PSY-FOUNDATION-VERSION: ${FOUNDATION_VERSION} */`
const outfile = join(outdir, naming)

console.log(`building ${entrypoint} → ${outfile}`)

let usedFormat = 'iife'
let result = await Bun.build({
  entrypoints: [entrypoint],
  outdir,
  naming,
  target: 'browser',
  format: 'iife',
  minify: false,
  banner,
})

if (!result.success) {
  // Some Bun versions do not support format:'iife'. ES modules are equally
  // valid for audioWorklet.addModule — note the fallback and retry.
  console.warn(
    "Bun.build rejected format:'iife' — falling back to 'esm' " +
      '(audioWorklet.addModule supports ES modules).'
  )
  usedFormat = 'esm'
  result = await Bun.build({
    entrypoints: [entrypoint],
    outdir,
    naming,
    target: 'browser',
    format: 'esm',
    minify: false,
    banner,
  })
}

if (!result.success) {
  console.error('worklet build FAILED:')
  for (const log of result.logs) console.error(String(log))
  process.exit(1)
}

const code = readFileSync(outfile, 'utf8')

// ── Assertion 1: registration present ──────────────────────────────────────
if (!code.includes("'psy4-processor'") && !code.includes('"psy4-processor"')) {
  console.error('worklet build FAILED: registration name psy4-processor not found in output')
  process.exit(1)
}

// ── Assertion 2: syntactically valid (node --check) ────────────────────────
// NOTE: run the real `node` binary — under Bun, process.execPath IS bun, and
// `bun <file>` executes the file instead of only checking its syntax.
try {
  execFileSync('node', ['--check', outfile], { stdio: 'pipe' })
} catch (err) {
  console.error('worklet build FAILED: node --check rejected the output')
  console.error(String(err?.stderr ?? err))
  process.exit(1)
}

// ── Assertion 3: version string embedded (PLAN_V3 3.1) ─────────────────────
if (!code.includes(`PSY-FOUNDATION-VERSION: ${FOUNDATION_VERSION}`)) {
  console.error(
    `worklet build FAILED: version marker PSY-FOUNDATION-VERSION: ${FOUNDATION_VERSION} missing from output`
  )
  process.exit(1)
}

const bytes = statSync(outfile).size
const md5 = createHash('md5').update(code).digest('hex')
console.log(
  `worklet build OK (format=${usedFormat}, ${bytes} bytes, md5=${md5}, version=${FOUNDATION_VERSION})`
)
